import { Avatar1, Avatar2, Avatar3, dummyUserIcon, insight1, insight2, insight3, insight4 } from '../assets/images';

export const INSIGHTS_DATA = [
  { slug: 'from-insight-to-impact', category: 'Insights', image: insight2, title: 'From Insight to Impact: Understanding Strategic Intelligence and Risk Management', author: 'Seth Stanton', avatar: Avatar1, date: '07 Apr, 2025', readTime: '2 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm." },
  { slug: 'why-strategic-intelligence-matters', category: 'News', image: insight3, title: 'Why Strategic Intelligence and Risk Awareness Matter More Than Ever', author: 'Bianca Fontana', avatar: Avatar2, date: '07 Apr, 2025', readTime: '3 min read', excerpt: 'Organizations that succeed are not those that avoid risk entirely, but those that understand it early.' },
  { slug: 'navigating-uncertainty', category: 'Casestudy', image: insight4, title: 'Navigating Uncertainty: The Role of Strategic Intelligence and Risk Concepts', author: 'Claudia Pridham', avatar: Avatar3, date: '07 Apr, 2025', readTime: '4 min read', excerpt: 'A deep dive into how leading organizations build resilience through strategic foresight.' },
  { slug: 'crisis-response-israel-iran', category: 'News', image: insight1, title: "Crisis Response Under Pressure: Sicuro Group's Israel-Iran Escalation Response", author: 'Shafiq B', avatar: dummyUserIcon, date: '16 Jan, 2025', readTime: '5 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm. Organizations that succeed are not those that avoid risk entirely, but those that understand it early and respond with clarity and confidence. This is where Strategic Intelligence and Risk Management play a critical role." },
  { slug: 'from-insight-to-impact', category: 'Insights', image: insight2, title: 'From Insight to Impact: Understanding Strategic Intelligence and Risk Management', author: 'Seth Stanton', avatar: Avatar1, date: '07 Apr, 2025', readTime: '2 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm." },
  { slug: 'why-strategic-intelligence-matters', category: 'News', image: insight3, title: 'Why Strategic Intelligence and Risk Awareness Matter More Than Ever', author: 'Bianca Fontana', avatar: Avatar2, date: '07 Apr, 2025', readTime: '3 min read', excerpt: 'Organizations that succeed are not those that avoid risk entirely, but those that understand it early.' },
  { slug: 'navigating-uncertainty', category: 'Casestudy', image: insight4, title: 'Navigating Uncertainty: The Role of Strategic Intelligence and Risk Concepts', author: 'Claudia Pridham', avatar: Avatar3, date: '07 Apr, 2025', readTime: '4 min read', excerpt: 'A deep dive into how leading organizations build resilience through strategic foresight.' },
  { slug: 'crisis-response-israel-iran', category: 'News', image: insight1, title: "Crisis Response Under Pressure: Sicuro Group's Israel-Iran Escalation Response", author: 'Shafiq B', avatar: dummyUserIcon, date: '16 Jan, 2025', readTime: '5 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm. Organizations that succeed are not those that avoid risk entirely, but those that understand it early and respond with clarity and confidence. This is where Strategic Intelligence and Risk Management play a critical role." },
  { slug: 'from-insight-to-impact', category: 'Insights', image: insight2, title: 'From Insight to Impact: Understanding Strategic Intelligence and Risk Management', author: 'Seth Stanton', avatar: Avatar1, date: '07 Apr, 2025', readTime: '2 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm." },
  { slug: 'why-strategic-intelligence-matters', category: 'News', image: insight3, title: 'Why Strategic Intelligence and Risk Awareness Matter More Than Ever', author: 'Bianca Fontana', avatar: Avatar2, date: '07 Apr, 2025', readTime: '3 min read', excerpt: 'Organizations that succeed are not those that avoid risk entirely, but those that understand it early.' },
  { slug: 'navigating-uncertainty', category: 'Casestudy', image: insight4, title: 'Navigating Uncertainty: The Role of Strategic Intelligence and Risk Concepts', author: 'Claudia Pridham', avatar: Avatar3, date: '07 Apr, 2025', readTime: '4 min read', excerpt: 'A deep dive into how leading organizations build resilience through strategic foresight.' },
  { slug: 'crisis-response-israel-iran', category: 'News', image: insight1, title: "Crisis Response Under Pressure: Sicuro Group's Israel-Iran Escalation Response", author: 'Shafiq B', avatar: dummyUserIcon, date: '16 Jan, 2025', readTime: '5 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm. Organizations that succeed are not those that avoid risk entirely, but those that understand it early and respond with clarity and confidence. This is where Strategic Intelligence and Risk Management play a critical role." },
  { slug: 'from-insight-to-impact', category: 'Insights', image: insight2, title: 'From Insight to Impact: Understanding Strategic Intelligence and Risk Management', author: 'Seth Stanton', avatar: Avatar1, date: '07 Apr, 2025', readTime: '2 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm." },
  { slug: 'why-strategic-intelligence-matters', category: 'News', image: insight3, title: 'Why Strategic Intelligence and Risk Awareness Matter More Than Ever', author: 'Bianca Fontana', avatar: Avatar2, date: '07 Apr, 2025', readTime: '3 min read', excerpt: 'Organizations that succeed are not those that avoid risk entirely, but those that understand it early.' },
  { slug: 'navigating-uncertainty', category: 'Casestudy', image: insight4, title: 'Navigating Uncertainty: The Role of Strategic Intelligence and Risk Concepts', author: 'Claudia Pridham', avatar: Avatar3, date: '07 Apr, 2025', readTime: '4 min read', excerpt: 'A deep dive into how leading organizations build resilience through strategic foresight.' },
  { slug: 'crisis-response-israel-iran', category: 'News', image: insight1, title: "Crisis Response Under Pressure: Sicuro Group's Israel-Iran Escalation Response", author: 'Shafiq B', avatar: dummyUserIcon, date: '16 Jan, 2025', readTime: '5 min read', excerpt: "In today's fast-changing business environment, uncertainty is no longer an exception, it is the norm. Organizations that succeed are not those that avoid risk entirely, but those that understand it early and respond with clarity and confidence. This is where Strategic Intelligence and Risk Management play a critical role." },
];
